theme = "solarized"

[editor]
rulers = [80]
auto-save = true
mouse = false
gutters = ["diff", "diagnostics", "spacer"]
auto-pairs = false
end-of-line-diagnostics = "hint"

  [editor.inline-diagnostics]
  cursor-line = "hint"

  [editor.cursor-shape]
  insert = "bar"
  normal = "block"
  select = "underline"

[keys.normal]
space.l = ":toggle lsp.display-inlay-hints"
