#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Alex Valiushko"
email = "alexvaliushko@tailscale.com"

[ui]
default-command = "log"
diff-formatter = [
    "difft",
    # "--display=inline",
    "--color=always",
    "--background=light",
    "--syntax-highlight=off",
    "$left",
    "$right",
  ]

[templates]
commit_trailers = '''
format_signed_off_by_trailer(self)
++ if(!trailers.contains_key("Change-Id"), format_gerrit_change_id_trailer(self))'''
